# Generated by Django 4.0.3 on 2022-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('attendance', models.IntegerField(default=0)),
                ('timeofattendance', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
