# Generated by Django 4.0.3 on 2022-04-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_timeofattendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='todays_attendance',
        ),
    ]
